const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Canon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Samsung Galaxy S21 Ultra 5G',
    image: '/images/phone2.jpg',
    description:
      'The Samsung Galaxy S21 Ultra 5G features a 108MP camera, 100x Space Zoom, and 5G capabilities. It’s a powerhouse of performance and innovation.',
    brand: 'Samsung',
    category: 'Electronics',
    price: 1199.99,
    countInStock: 15,
    rating: 4.8,
    numReviews: 22,
  },
  {
    _id: '8',
    name: 'Dell XPS 13 Laptop',
    image: '/images/laptop.jpg',
    description:
      'The Dell XPS 13 is a high-performance laptop with a stunning 4K display, long battery life, and sleek design.',
    brand: 'Dell',
    category: 'Computers',
    price: 999.99,
    countInStock: 8,
    rating: 4.7,
    numReviews: 19,
  },
  {
    _id: '9',
    name: 'Sony WH-1000XM4 Wireless Noise Cancelling Headphones',
    image: '/images/headphones.jpg',
    description:
      'The Sony WH-1000XM4 headphones offer industry-leading noise cancellation, superior sound quality, and long-lasting comfort.',
    brand: 'Sony',
    category: 'Electronics',
    price: 349.99,
    countInStock: 25,
    rating: 4.9,
    numReviews: 40,
  },
  {
    _id: '10',
    name: 'Bose SoundLink Revolve+ Bluetooth Speaker',
    image: '/images/speaker.jpg',
    description:
      'The Bose SoundLink Revolve+ is a portable Bluetooth speaker that delivers deep, loud, immersive sound in every direction.',
    brand: 'Bose',
    category: 'Audio',
    price: 299.99,
    countInStock: 10,
    rating: 4.8,
    numReviews: 30,
  },
  {
    _id: '11',
    name: 'Fitbit Charge 4 Fitness and Activity Tracker',
    image: '/images/fitbit.jpg',
    description:
      'The Fitbit Charge 4 tracks your workouts, heart rate, sleep, and more. It’s a must-have for fitness enthusiasts.',
    brand: 'Fitbit',
    category: 'Wearables',
    price: 129.99,
    countInStock: 20,
    rating: 4.4,
    numReviews: 55,
  },
  {
    _id: '12',
    name: 'Microsoft Surface Pro 7',
    image: '/images/surface.jpg',
    description:
      'The Microsoft Surface Pro 7 is a versatile 2-in-1 device that combines the power of a laptop with the flexibility of a tablet.',
    brand: 'Microsoft',
    category: 'Computers',
    price: 899.99,
    countInStock: 12,
    rating: 4.6,
    numReviews: 25,
  },
  {
    _id: '13',
    name: 'Apple Watch Series 6',
    image: '/images/applewatch.jpg',
    description:
      'The Apple Watch Series 6 helps you measure your blood oxygen level, track your workouts, and stay connected with friends and family.',
    brand: 'Apple',
    category: 'Wearables',
    price: 399.99,
    countInStock: 18,
    rating: 4.9,
    numReviews: 60,
  },
  {
    _id: '14',
    name: 'GoPro HERO9 Black Action Camera',
    image: '/images/gopro.jpg',
    description:
      'The GoPro HERO9 Black captures stunning 5K video and 20MP photos. It’s built tough and waterproof for all your adventures.',
    brand: 'GoPro',
    category: 'Cameras',
    price: 449.99,
    countInStock: 9,
    rating: 4.5,
    numReviews: 35,
  },
  {
    _id: '15',
    name: 'Nikon D3500 DSLR Camera',
    image: '/images/nikon.jpg',
    description:
      'The Nikon D3500 is an entry-level DSLR that’s perfect for beginners. It’s easy to use and delivers high-quality images.',
    brand: 'Nikon',
    category: 'Cameras',
    price: 499.99,
    countInStock: 14,
    rating: 4.3,
    numReviews: 27,
  },
  {
    _id: '16',
    name: 'Sony Bravia 55-inch 4K Ultra HD Smart LED TV',
    image: '/images/tv.jpg',
    description:
      'The Sony Bravia 55-inch 4K Ultra HD Smart LED TV offers stunning picture quality, vibrant colors, and smart features.',
    brand: 'Sony',
    category: 'Electronics',
    price: 799.99,
    countInStock: 6,
    rating: 4.7,
    numReviews: 45,
  },
  {
    _id: '17',
    name: 'Samsung Galaxy Tab S7',
    image: '/images/tablet.jpg',
    description:
      'The Samsung Galaxy Tab S7 features a powerful processor, a stunning display, and the versatility of an Android tablet.',
    brand: 'Samsung',
    category: 'Tablets',
    price: 649.99,
    countInStock: 10,
    rating: 4.6,
    numReviews: 33,
  },
  {
    _id: '18',
    name: 'Asus ROG Strix Gaming Laptop',
    image: '/images/gaminglaptop.jpg',
    description:
      'The Asus ROG Strix Gaming Laptop delivers high-performance gaming with a powerful processor, advanced graphics, and a sleek design.',
    brand: 'Asus',
    category: 'Computers',
    price: 1499.99,
    countInStock: 5,
    rating: 4.8,
    numReviews: 20,
  },
  {
    _id: '19',
    name: 'Canon PIXMA Wireless All-in-One Printer',
    image: '/images/printer.jpg',
    description:
      'The Canon PIXMA Wireless All-in-One Printer offers high-quality printing, scanning, and copying. It’s perfect for home and office use.',
    brand: 'Canon',
    category: 'Office Supplies',
    price: 99.99,
    countInStock: 8,
    rating: 4.2,
    numReviews: 18,
  },
  {
    _id: '20',
    name: 'HP Envy Photo 7855 All-in-One Printer',
    image: '/images/hpprinter.jpg',
    description:
      'The HP Envy Photo 7855 All-in-One Printer delivers stunning photo prints, easy wireless printing, and a sleek design.',
    brand: 'HP',
    category: 'Office Supplies',
    price: 199.99,
    countInStock: 7,
    rating: 4.4,
    numReviews: 22,
  },
  {
    _id: '21',
    name: 'Roku Streaming Stick+',
    image: '/images/rokustick.jpg',
    description:
      'The Roku Streaming Stick+ provides 4K HDR streaming with a long-range wireless receiver and easy setup.',
    brand: 'Roku',
    category: 'Electronics',
    price: 49.99,
    countInStock: 30,
    rating: 4.7,
    numReviews: 50,
  },
  {
    _id: '22',
    name: 'Anker PowerCore 10000 Portable Charger',
    image: '/images/powerbank.jpg',
    description:
      'The Anker PowerCore 10000 is a compact, high-capacity portable charger that provides fast and safe charging for your devices.',
    brand: 'Anker',
    category: 'Accessories',
    price: 25.99,
    countInStock: 40,
    rating: 4.8,
    numReviews: 55,
  },
  {
    _id: '23',
    name: 'Apple MacBook Pro 16-inch',
    image: '/images/macbook.jpg',
    description:
      'The Apple MacBook Pro 16-inch features a powerful processor, stunning Retina display, and long battery life.',
    brand: 'Apple',
    category: 'Computers',
    price: 2399.99,
    countInStock: 4,
    rating: 4.9,
    numReviews: 18,
  },
  {
    _id: '24',
    name: 'Google Nest Hub Max',
    image: '/images/nesthub.jpg',
    description:
      'The Google Nest Hub Max offers a 10-inch display, built-in Google Assistant, and smart home controls.',
    brand: 'Google',
    category: 'Smart Home',
    price: 229.99,
    countInStock: 15,
    rating: 4.6,
    numReviews: 25,
  },
  {
    _id: '25',
    name: 'Kindle Paperwhite E-Reader',
    image: '/images/kindle.jpg',
    description:
      'The Kindle Paperwhite E-Reader features a high-resolution display, waterproof design, and adjustable lighting.',
    brand: 'Amazon',
    category: 'Books',
    price: 129.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 40,
  },
  {
    _id: '26',
    name: 'JBL Flip 5 Portable Waterproof Speaker',
    image: '/images/jblspeaker.jpg',
    description:
      'The JBL Flip 5 is a portable waterproof speaker with powerful sound, a durable design, and up to 12 hours of playtime.',
    brand: 'JBL',
    category: 'Audio',
    price: 119.99,
    countInStock: 25,
    rating: 4.7,
    numReviews: 35,
  },
  {
    _id: '27',
    name: 'Oculus Quest 2 VR Headset',
    image: '/images/oculus.jpg',
    description:
    'The JBL Flip 5 is a portable waterproof speaker with powerful sound, a durable design, and up to 12 hours of playtime.',
    brand: 'JBL',
    category: 'Audio',
    price: 119.99,
    countInStock: 25,
    rating: 4.7,
    numReviews: 35,
  }
]

export default products
